import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import Footer from '@/components/footer';
import './globals.css';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`flex h-screen flex-col ${notoSansJP.className}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
